[package]
name = "imxrt-usdhc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "USDHC SD card driver for NXP's i.MX RT MCUs"
repository = "https://github.com/acertain/imxrt-usdhc"
readme = "README.md"
keywords = ["imxrt", "nxp", "sd", "sdcard", "embedded-sdmmc"]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]

[dependencies]
imxrt-ral = "0.6"
cortex-m = "0.7"
defmt = { version = "0.3", optional = true }

[dependencies.embedded-sdmmc]
version = "0.9"

[features]
defmt = ["dep:defmt"]

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
features = ["imxrt-ral/imxrt1062"]
